---
- name: This playbook is to create user
  hosts: all
  become: true
  vars:
    user: modi
  tasks:
  - name: Creating user john
    user:
      name: "{{ user }}"
    # This also works
    #user: name=john 
