- name: This playbook install apache
  hosts: all
  become: true
  #gather_facts: no
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: installed
      #notify: Start service httpd
    when: ansible_os_family == "RedHat"
    tags: install_apache
  - name: Start service httpd
    service: 
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"  
    tags: start_apache
  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"  
    tags: install_apache
  - name: Start service apache2
    service: 
      name: apache2
      state: started
    when: ansible_os_family == "Debian"  
    tags: start_apache
  - name: copy index.html file
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
      #owner: john
      #group: john

