---
- name: This playbook install packages
  hosts: webservers
  become: true
  tasks:
  - name: Install package
    yum:
      name: ['git', 'make', 'gcc', 'wget', 'telnet', 'gzip']
      state: installed
