---
- name: Setup tomcat
  hosts: all
  become: true
  tasks:
  - name: Install Java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
  - name: install java on Ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
  - name: Download tomcat packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz
      dest: /opt
  - name: Untar apache packages
    unarchive:
      src: /opt/apache-tomcat-8.5.82.tar.gz
      dest: /opt
      remote_src: yes
  - name: Give executing permission
    file:
      path: /opt/apache-tomcat-8.5.82/bin/startup.sh
      #owner:
      #group:
      mode: 0777
  - name: Start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.82/bin/
