---
- name: This playbook uninstall httpd and apache
  hosts: all
  become: true
  tasks:
  - name: Stop httpd
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"
  - name: Uninstall httpd
    yum: 
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"  
  - name: Stop apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"  
  - name: Uninstall apache2
    apt: 
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"  
